version: '3.9'

services:

  bdb:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: BUYB2QAZ
      POSTGRES_USER: postgres
      POSTGRES_DB: dbname
    restart: always
    ports:
      - "5432:5432"

  my-app:
    container_name: my-app
    build:
      context: my-app
      dockerfile: Dockerfile
    volumes:
      - ./my-app:/usr/src/my-app
      # One-way volume to use node_modules from inside image
      - /usr/src/my-app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - bweb
    command: npm start

  bweb:
    container_name: bweb
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/backend/manage.py makemigrations --noinput &&
             python /usr/src/backend/manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python /usr/src/backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: BUYB2QAZ
      POSTGRES_USER: postgres
      POSTGRES_DB: dbname
    depends_on:
      - bdb

volumes:
  postgres_data: